### ISSUE TITLE
Uncaught TypeError: fela_plugin_validator_1.default is not a function

### ISSUE THREAD

**Issue by veeramarni** [rofrischmann/fela#248] opened 2017-04-25 22:56 UTC
**Version**: 4.3.2
**Environment**: DOM
**Type**: Bug

-------------------
#### Description
When bundle with webpack, i get the following error. 
```
Uncaught TypeError: fela_plugin_validator_1.default is not a function
```
I use typescript and use webpack to bundle it. Below is how I have imported it. 
```
import validator from 'fela-plugin-validator';
```

I don't have this issue if use `require` instead. 
```
const validator = require('fela-plugin-validator');
```

**Comment by tajo** [comment] 2017-04-25 22:59
Do you use webpack2 ?

**Comment by veeramarni** [comment] 2017-04-25 23:00
Yes, I'm using webpack v2.3.3

**Comment by rofrischmann** [comment] 2017-05-02 07:11
I'm not able to reproduce that right now :/

**Comment by tajo** [comment] 2017-05-03 08:58
@veeramarni Do you use es2015 babel preset? If so, did you set modules to false?

try something like this

```
"presets": [
  ["es2015", { "modules": false }],
   "react"
]
```

**Comment by rofrischmann** [comment] 2017-05-10 14:38
Closing this for now. We might check back after switching to Lerna @tajo

**Closed by rofrischmann** 2017-05-10 14:38 UTC
Labels: help wanted, no-repro

**Comment by veeramarni** [comment] 2017-05-10 15:22
@tajo We don't need babel preset as we use typescript.

**Comment by tajo** [comment] 2017-05-10 15:42
@veeramarni well, you should try the similar thing for TS as well: 

https://github.com/blacksonic/typescript-webpack-tree-shaking/blob/master/tsconfig.es2015.json#L6
