### ISSUE TITLE
Compose passThroughProps

### ISSUE THREAD

**Issue by kserjey** [rofrischmann/fela#592] opened 2018-08-06 08:42 UTC
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela     | 6.1.9   |
| fela-preset-web | 8.0.8 |
| react-fela | 7.3.1 |

-------------------

#### Description

I have a primitive styled component (ex. `Button`) and want to create another component on top of that primitive (ex. `SuperButton`) with props to dynamically change styles. My primitive component passes all props to HTML element to act just like normal button with some predefined styles. I expect that `SuperButton` does not pass props through but it happens...

#### Steps to reproduce

[CodeSandbox](https://codesandbox.io/s/nk0v98mon4)

#### Proposal

I think it happens because `resolvedPassThrough` are used to filter props only if current element isn't `FelaComponent`.

https://github.com/rofrischmann/fela/blob/9d22b1371435a8b4f19088ae3f92c055e8f30377/packages/fela-bindings/src/createComponentFactory.js#L67-L98

**Comment by rofrischmann** [comment] 2018-08-11 16:14
This looks like a duplicate of #538 
Will close it here, but thanks for reporting.

**Closed by rofrischmann** 2018-08-11 16:14 UTC
