### ISSUE TITLE
Enzyme shallow output does not match expectations

### ISSUE THREAD

**Issue by HamidAghdaee** [rofrischmann/fela#494] opened 2018-01-05 02:10 UTC
**Type**: Bug 

| Packages | Version |
| -------- | ------- |
| fela     | 6.1.3   |
| enzyme     | 3.3.0   |
| fela-tools     | 5.1.2   |
| react     | 16.2.0   |
| react-fela    | 6.2.4   |
| enzyme-adapter-react-16 | 1.1.1|

-------------------
#### Description
When using enzyme shallow rendering, the output does not render Fela styles.

#### Steps to reproduce
I took the code from here: http://fela.js.org/docs/recipes/TestingFelaComponents.html
and added it to Repo: https://github.com/HamidAghdaee/test-fela

steps:
Clone Repo
yarn test

#### Expected Behavior
According to: 
http://fela.js.org/docs/recipes/TestingFelaComponents.html
the output of ```container.snapshot()``` in here: https://github.com/HamidAghdaee/test-fela/blob/master/src/Box.test.js#L8 should be:
```javascript
// Object {
//   "component": <div
//     className="a b c"
// >
//     hello
// </div>,
//   "styles": ".a{width:10px}.b{height:10px}.c{background-color:red}",
// }
```

#### Actual Behavior
instead the snapshot provided here:
https://github.com/HamidAghdaee/test-fela/blob/master/src/__snapshots__/Box.test.js.snap
shows 
```javascript
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`renders without crashing 1`] = `
<boxRules
  _felaTheme={Object {}}
>
  hello
</boxRules>
`;

exports[`renders without crashing 2`] = `""`;
```
I'm not sure if this is related but calling `render()` on the enzyme wrapper results in the following error even-though the renderer is indeed placed in the context:

```    createComponent() can't render styles without the renderer in the context. Missing react-fela's <Provider /> at the app root?
```

**Comment by rofrischmann** [comment] 2018-01-05 13:16
I guess this is due to changes in Enzyme 3 (for React 16).
It works perfectly fine if I use 2 and 15 as used in the docs. I am not really sure how to fix it for Enzyme 3 actually, but it's definitely not a bug in Fela itself.

**Comment by HamidAghdaee** [comment] 2018-01-05 17:42
@rofrischmann Dang. Thanks for looking into this. That's a bummer. We're trying to do stateful shallow testing of our components in React 16. As it is I can't think of a good solution until this is fixed. 

`renderer` from `react-test-renderer` will give us the full DOM Tree, with styles and all but it is the full render of the entire tree and now shallow. `ShallowRenderer` from the same library doesn't give us the ability to get an abstraction of the component instance and do stateful testing with it. 

Let me know if you have any other thoughts. Thank you again.

**Comment by rofrischmann** [comment] 2018-01-11 21:30
Hmm. I am afraid I do not know any simple solution to that. I actually only test components with `react-test-renderer`. I will eventually close this issue right here. Feel free to reopen if it turns out to be something wrong with Fela.

**Closed by rofrischmann** 2018-01-11 21:30 UTC

**Comment by HamidAghdaee** [comment] 2018-02-26 23:56
@rofrischmann 

In response to this issue, I came up with a solution which is working for us at Cloudflare:

https://github.com/HamidAghdaee/test-fela

I would be interested in open-sourcing it. what do you think? how would we go about doing that?

**Comment by rofrischmann** [comment] 2018-02-27 08:29
I would love to see that happening :) 
You can either release it yourself and add it to the docs, or directly send a PR to add it to the Fela monorepo and benefit from the integrity of the repository =)

Love to see that ppl are building solutions for common problems I am not aware of!
Great work.
