### ISSUE TITLE
Issue when using fela-plugin-embedded `fontFace` using multiple fonts with same `familyName`

### ISSUE THREAD

**Issue by Cowboy-coder** [rofrischmann/fela#448] opened 2017-10-24 11:18 UTC
**Version**: 6.0.x
**Environment**: Both
**Type**: Bug

-------------------
#### Description
I expect 
```js
const rule = () => ({
  fontFace: [
    {
      fontFamily: 'Arial',
      src: ['arial-regular.svg', 'arial-regular.ttf'],
      fontWeight: 400
    },
    {
      fontFamily: 'Arial',
      src: ['arial-bold.svg', 'arial-bold.ttf'],
      fontWeight: 700
    }
  ]
})
```
to render 
```css
@font-face{
  font-weight:400;
  src:url('arial-regular.svg') format('svg'),url('arial-regular.ttf') format('truetype');
  font-family:\"Arial\"
}
@font-face{
  font-weight:700;
  src:url('arial-bold.svg') format('svg'),url('arial-bold.ttf') format('truetype');
  font-family:\"Arial\"
}
```
and on the element:
```css
.a {
  font-family:"Arial"
}
```
but instead I get 
```css
.a {
  font-family:"Arial", "Arial"
}
```
on the element.

#### Steps to reproduce
1. First step
2. Second step

#### Proposal

I haven't digged into how to solve this or even if this should be solved like this, but I think it makes sense?

In any case, I have reproduced the error in a test-case:
```js
it('should render inline fonts with same fontFamily', () => {
  const rule = () => ({
    color: 'red',
    fontFace: [
      {
        fontFamily: 'Arial',
        src: ['arial-regular.svg', 'arial-regular.ttf'],
        fontWeight: 400
      },
      {
        fontFamily: 'Arial',
        src: ['arial-bold.svg', 'arial-bold.ttf'],
        fontWeight: 700
      }
    ]
  })

  const renderer = createRenderer({
    plugins: [embedded()]
  })
  renderer.renderRule(rule)

  expect(renderToString(renderer)).toEqual(
    "@font-face{font-weight:400;src:url('arial-regular.svg') format('svg'),url('arial-regular.ttf') format('truetype');font-family:\"Arial\"}@font-face{font-weight:700;src:url('arial-bold.svg') format('svg'),url('arial-bold.ttf') format('truetype');font-family:\"Arial\"}" +
      '.a{color:red}.c{font-family:"Arial"}'
  )
})
```
inside of `fela-plugin-embedded`.

**EDIT:**

One extra feature which I think makes sense is to be able to override the `familyName` as well:
```js
{
  fontFace: [
    {
      fontFamily: 'Arial',
      src: ['arial-regular.svg', 'arial-regular.ttf'],
      fontWeight: 400
    },
    {
      fontFamily: 'Arial',
      src: ['arial-bold.svg', 'arial-bold.ttf'],
      fontWeight: 700
    }
  ],
  fontFamily: 'Arial, sans-serif',
}
```
should generate `fontFamily: 'Arial, sans-serif'` on the element. Right now it becomes `Arial` (or `Arial, Arial` with this bug).

**Comment by rofrischmann** [comment] 2017-10-24 23:01
Actually, this is exactly what @TxHawks proposed over at Gitter as well I guess.
We should definitely improve the whole part of rendering fonts in Fela!

**Comment by TxHawks** [comment] 2017-10-25 03:48
This is a duplicate of #437. I just ended up doing this directly with `renderFont` at the same place I do all my `renderStatic`, and am quite happy with it:

```js
styleRenderer.renderFont(
    '"Open Sans Hebrew"',
    [
      '../src/fonts/OpenSansHebrewRegular.woff',
      '../src/fonts/OpenSansHebrewRegular.woff2',
    ],
    { fontWeight: 400, }
  );
  styleRenderer.renderFont(
    '"Open Sans Hebrew"',
    [
      '../src/fonts/OpenSansHebrewBold.woff',
      '../src/fonts/OpenSansHebrewBold.woff2',
    ],
    { fontWeight: 700, }
  );

  styleRenderer.renderStatic(globalRules)
```
I actually think it makes sense to load webfonts there.

That said, I do think there is room to ogger more advanced font loading techniques (see [here](https://www.zachleat.com/web/recipes/) and intend to work on it soon.

**Comment by rofrischmann** [comment] 2017-10-27 01:29
Yeah, I will close this one as we kind of have an issue already. That's definitely something we'll be working on soon, but there's a reasonable solution up there as well :)

**Closed by rofrischmann** 2017-10-27 01:29 UTC
