### ISSUE TITLE
[React] Warning: Prop `className` did not match. Server: "oih oii" Client: "oif oig"

### ISSUE THREAD

**Issue by bkniffler** [rofrischmann/fela#378] opened 2017-09-17 16:16 UTC
**Version**: 5.2.0 (latest)
**Environment**: DOM
**Type**: Bug

-------------------
#### Description
If I use the latest versions with react 16 in my SSR enabled app and the latest fela, I'm often getting classname mismatches on rehydration, most often on more complex sites with lots of fela components. Also, the layout will be off (some fela styles are missing). After navigating around on the page, the layout is corrected. 

It seems like there is a problem on fela rehydration when classnames don't match, though I don't know why there is a mismatch in the first place, everything else in the markup is the same. When I turn off SSR, there is no problem with the initial layout.

I'm using the same code as in the current react example, so fela-dom and renderToMarkup.

I've tried to isolate the issue into a small project, but I've not succeeded. I suppose that this only happens with a lot of components and heavy use of fela. 

Do you have any idea what this could be due, have you stumbled upon this maybe?

This is the fela config: https://github.com/olymp/olymp/blob/vertical-nav/packages/fela/utils/create-fela.es6
This is the server init: https://github.com/olymp/olymp/blob/vertical-nav/packages/core/node/server.es6#L189
This is the web init: https://github.com/olymp/olymp/blob/vertical-nav/packages/core/web/index.es6#L154

I'll definitely look more into this.

**Comment by rofrischmann** [comment] 2017-09-17 16:23
I will check that later! Actually with the current version on npm, Fela doesn't rehydrate anything at all, so there should not be an issue with that.

Are you using Apollo or sth. like that? We sometimes had issues with SSR because of how Apollo's renderDeepTree (sth. like that) did something strange.

**Comment by bkniffler** [comment] 2017-09-17 16:26
Thanks for the quick response, yes, I'm using apollo link and the getDataFromTree stuff (https://github.com/olymp/olymp/blob/vertical-nav/packages/core/node/server.es6#L227)!

**Comment by rofrischmann** [comment] 2017-09-17 16:39
As far as I know, there was an issue with Apollo's getDataFromTree as it didn't resolve the components in the same order React did (or sth. like that, can't really remember...) Maybe @steida knows what the exact issue was?

Anyways, I am already working on rehydration, so soon this issue might even be fixed once for all. Looks promising already, but I need to write some more tests :)

**Comment by bkniffler** [comment] 2017-09-17 19:04
Okay, I'll just wait for the fix and see if it helps for my case. For now, using fela-monolithic seems to fix the issue. Can you ping me when you released the fix?

**Comment by steida** [comment] 2017-09-17 19:08
Fela is ok. There is a bug in your code. Maybe flush or something, follow the exactly Next.js example.

**Comment by rofrischmann** [comment] 2017-09-22 16:38
I will close this now. You could retry with Fela 6.0 in some mins, but if you still have a problem, it most likely is caused by Apollo.

**Closed by rofrischmann** 2017-09-22 16:38 UTC

**Comment by marhalpert** [comment] 2017-11-01 00:09
I had the same problem, I restarted the dev server and then the error was gone.
