### ISSUE TITLE
Fela bindings does not export RendererProviderFactory

### ISSUE THREAD

**Issue by studna** [rofrischmann/fela#698] opened 2019-04-09 15:59 UTC
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela-bindings     | 10.2.3   |

-------------------
#### Description
Package `fela-bindings@10.2.3` does not export **RendererProviderFactory**. It's wierd, because the master branch looks fine https://github.com/rofrischmann/fela/blob/master/packages/fela-bindings/src/index.js#L15.

#### Error Message
```
./node_modules/react-fela/es/RendererProvider.js
Attempted import error: 'RendererProviderFactory' is not exported from 'fela-bindings'.
```

#### Steps to reproduce

1. `yarn add fela-bindings@10.2.3`
2. `cat node_modules/fela-bindings/es/index.js`
```
import connectFactory from './connectFactory';
import createComponentFactory from './createComponentFactory';
import FelaComponentFactory from './FelaComponentFactory';
import FelaThemeFactory from './FelaThemeFactory';
import ProviderFactory from './ProviderFactory';
import ThemeProviderFactory from './ThemeProviderFactory';
import withThemeFactory from './withThemeFactory';
import createTheme from './createTheme';
import feFactory from './feFactory';
import { THEME_CHANNEL } from './themeChannel';

export { connectFactory, createComponentFactory, FelaComponentFactory, FelaThemeFactory, ProviderFactory, ThemeProviderFactory, withThemeFactory, createTheme, feFactory, THEME_CHANNEL };
```

**Comment by studna** [comment] 2019-04-09 16:31
Same issue with `fela-plugin-prefixer@10.2.3`. In NPM package is line `import prefix from 'inline-style-prefixer/static';` instead of https://github.com/rofrischmann/fela/blob/master/packages/fela-plugin-prefixer/src/index.js#L2

Looks like some build issue.

**Comment by reinhard** [comment] 2019-04-09 16:47
I can confirm this problem with Fela 10.2.3

**Comment by rofrischmann** [comment] 2019-04-09 17:05
Oh wtf. those are completely wrong versions out as 10.2.3

**Comment by TxHawks** [comment] 2019-04-09 17:06
Looks like something went wrong wrong when publishing. Building the repository produces the correct bundles

@rofrischmann should I bump a patch version and re-publish?

**Comment by rofrischmann** [comment] 2019-04-09 17:07
@TxHawks If you could do that real quick, I'd be more than happy!
Maybe it is linked to the fela@6.2.4 release I did using the v6-tag?

**Comment by TxHawks** [comment] 2019-04-09 17:37
@rofrischmann I don't have permissions for publishing `fela-codemods` so only some packages were published, and others (that happen to be after `fela-codemods` in the publishing order, did not)

**Comment by TxHawks** [comment] 2019-04-09 18:05
Version `10.2.24` of all packages except `fela-codemeds`, `fela-enzyme`, `jest-fela-bindings`, `jest-inferno-fela`, `jest-preact-fela` and `jest-react-fela`, to which I don't have permissions in npm have been published. I check the published code, and everything seems fine now.

@studna can you reinstall and confirm the issue has been resolved.

**Comment by studna** [comment] 2019-04-09 18:10
@TxHawks 10.2.4 works great. Thank you! 👍

**Comment by TxHawks** [comment] 2019-04-09 18:12
Great. Will close this once @rofrischmann has a moment to publish the remaining packages.

**Comment by rofrischmann** [comment] 2019-04-10 12:45
Ill merge a fix soon and just publish 10.2.5 directly

**Comment by TxHawks** [comment] 2019-04-10 12:47
Fix?

**Comment by rofrischmann** [comment] 2019-04-10 13:05
Oh I meant a small patch (see #700). But I can also just release now first. Ultimately we wanna get the npm org and move to scoped packages :)

**Closed** 2019-05-06 09:39 UTC
